-- The Final Test · instalación completa de la base de datos (D1).
-- Una sentencia por línea; se puede ejecutar las veces que haga falta: no borra ni cambia datos.
-- Es schema.sql sin comentarios. Pégalo entero en la consola de D1 o ejecútalo con:
--   npx wrangler d1 execute axioma --remote --file=instalar.sql
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT NOT NULL, name TEXT, picture TEXT, created_at INTEGER NOT NULL, last_seen INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS scores (user_id TEXT NOT NULL REFERENCES users(id), day INTEGER NOT NULL, moves INTEGER NOT NULL, hints INTEGER NOT NULL DEFAULT 0, seconds INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, PRIMARY KEY (user_id, day));
CREATE INDEX IF NOT EXISTS scores_day ON scores(day, moves, hints, created_at);
CREATE TABLE IF NOT EXISTS sudoku (user_id TEXT NOT NULL REFERENCES users(id), day INTEGER NOT NULL, level INTEGER NOT NULL, seconds INTEGER NOT NULL, errors INTEGER NOT NULL DEFAULT 0, hints INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, PRIMARY KEY (user_id, day, level));
CREATE INDEX IF NOT EXISTS sudoku_day ON sudoku(day, level, seconds, created_at);
CREATE TABLE IF NOT EXISTS events (code TEXT PRIMARY KEY, name TEXT NOT NULL, owner_id TEXT NOT NULL REFERENCES users(id), game TEXT NOT NULL DEFAULT 'sudoku', level INTEGER NOT NULL DEFAULT 0, mode TEXT NOT NULL DEFAULT 'solo', team_size INTEGER NOT NULL DEFAULT 1, pace TEXT NOT NULL DEFAULT 'diario', start_day INTEGER NOT NULL, rounds INTEGER NOT NULL, days INTEGER NOT NULL DEFAULT 1, prize TEXT, forfeit TEXT, seed INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS event_rounds (event_code TEXT NOT NULL REFERENCES events(code), round INTEGER NOT NULL, puzzle TEXT NOT NULL, solution TEXT NOT NULL, PRIMARY KEY (event_code, round));
CREATE TABLE IF NOT EXISTS event_members (event_code TEXT NOT NULL REFERENCES events(code), user_id TEXT NOT NULL REFERENCES users(id), team TEXT, joined_at INTEGER NOT NULL, PRIMARY KEY (event_code, user_id));
CREATE TABLE IF NOT EXISTS event_starts (event_code TEXT NOT NULL, round INTEGER NOT NULL, user_id TEXT NOT NULL, started_at INTEGER NOT NULL, PRIMARY KEY (event_code, round, user_id));
CREATE TABLE IF NOT EXISTS event_results (event_code TEXT NOT NULL, round INTEGER NOT NULL, user_id TEXT NOT NULL, team TEXT, seconds INTEGER NOT NULL, score INTEGER NOT NULL DEFAULT 0, errors INTEGER NOT NULL DEFAULT 0, hints INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, PRIMARY KEY (event_code, round, user_id));
CREATE INDEX IF NOT EXISTS event_results_code ON event_results(event_code, round, seconds);
CREATE TABLE IF NOT EXISTS coop (code TEXT PRIMARY KEY, level INTEGER NOT NULL, puzzle TEXT NOT NULL, solution TEXT NOT NULL, owner_id TEXT NOT NULL REFERENCES users(id), event_code TEXT, round INTEGER, started_at INTEGER, finished_at INTEGER, errors INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS coop_members (code TEXT NOT NULL REFERENCES coop(code), user_id TEXT NOT NULL REFERENCES users(id), joined_at INTEGER NOT NULL, PRIMARY KEY (code, user_id));
CREATE TABLE IF NOT EXISTS coop_moves (code TEXT NOT NULL, seq INTEGER NOT NULL, user_id TEXT NOT NULL, k INTEGER NOT NULL, v INTEGER NOT NULL, created_at INTEGER NOT NULL, PRIMARY KEY (code, seq));
CREATE TABLE IF NOT EXISTS contests (code TEXT PRIMARY KEY, name TEXT NOT NULL, owner_id TEXT NOT NULL REFERENCES users(id), prize TEXT, description TEXT, level INTEGER NOT NULL, max_errors INTEGER NOT NULL, max_questions INTEGER NOT NULL, seconds_per_q INTEGER NOT NULL, math INTEGER NOT NULL DEFAULT 1, public INTEGER NOT NULL DEFAULT 0, starts_at INTEGER NOT NULL, ends_at INTEGER NOT NULL, seed INTEGER NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS contests_public ON contests(public, ends_at);
CREATE TABLE IF NOT EXISTS contest_entries (code TEXT NOT NULL REFERENCES contests(code), user_id TEXT NOT NULL REFERENCES users(id), joined_at INTEGER NOT NULL, started_at INTEGER, finished_at INTEGER, end_reason TEXT, idx INTEGER NOT NULL DEFAULT 0, correct INTEGER NOT NULL DEFAULT 0, errors INTEGER NOT NULL DEFAULT 0, total_ms INTEGER NOT NULL DEFAULT 0, q_sent_at INTEGER, PRIMARY KEY (code, user_id));
CREATE INDEX IF NOT EXISTS contest_entries_rank ON contest_entries(code, correct, errors, total_ms);
CREATE TABLE IF NOT EXISTS contest_answers (code TEXT NOT NULL, user_id TEXT NOT NULL, idx INTEGER NOT NULL, chosen INTEGER NOT NULL, ok INTEGER NOT NULL, ms INTEGER NOT NULL, PRIMARY KEY (code, user_id, idx));
CREATE TABLE IF NOT EXISTS profiles (user_id TEXT PRIMARY KEY REFERENCES users(id), birthdate TEXT, terms_version TEXT, terms_at INTEGER, guardian_name TEXT, guardian_email TEXT, guardian_ok INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS orgs (id TEXT PRIMARY KEY, name TEXT NOT NULL, kind TEXT NOT NULL, email_domain TEXT, levels TEXT NOT NULL, status TEXT NOT NULL, teacher_code TEXT NOT NULL, created_by TEXT NOT NULL REFERENCES users(id), created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS org_members (org_id TEXT NOT NULL REFERENCES orgs(id), user_id TEXT NOT NULL REFERENCES users(id), role TEXT NOT NULL, student_code TEXT, consent_ok INTEGER NOT NULL DEFAULT 0, joined_at INTEGER NOT NULL, PRIMARY KEY (org_id, user_id));
CREATE INDEX IF NOT EXISTS org_members_user ON org_members(user_id);
CREATE TABLE IF NOT EXISTS org_units (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id TEXT NOT NULL REFERENCES orgs(id), parent_id INTEGER, depth INTEGER NOT NULL, name TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS org_units_org ON org_units(org_id, depth);
CREATE TABLE IF NOT EXISTS courses (code TEXT PRIMARY KEY, org_id TEXT NOT NULL REFERENCES orgs(id), unit_id INTEGER, name TEXT NOT NULL, term TEXT, owner_id TEXT NOT NULL REFERENCES users(id), approval INTEGER NOT NULL DEFAULT 0, archived INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS courses_org ON courses(org_id);
CREATE TABLE IF NOT EXISTS course_members (code TEXT NOT NULL REFERENCES courses(code), user_id TEXT NOT NULL REFERENCES users(id), role TEXT NOT NULL, status TEXT NOT NULL, joined_at INTEGER NOT NULL, PRIMARY KEY (code, user_id));
CREATE INDEX IF NOT EXISTS course_members_user ON course_members(user_id);
CREATE TABLE IF NOT EXISTS banks (id INTEGER PRIMARY KEY AUTOINCREMENT, org_id TEXT NOT NULL REFERENCES orgs(id), owner_id TEXT NOT NULL REFERENCES users(id), name TEXT NOT NULL, unit_id INTEGER, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS bank_questions (id INTEGER PRIMARY KEY AUTOINCREMENT, bank_id INTEGER NOT NULL REFERENCES banks(id), level INTEGER NOT NULL, topic TEXT, q TEXT NOT NULL, opts TEXT NOT NULL, answer INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS bank_questions_bank ON bank_questions(bank_id);
CREATE TABLE IF NOT EXISTS contest_scope (code TEXT PRIMARY KEY REFERENCES contests(code), kind TEXT NOT NULL, audience TEXT NOT NULL, org_id TEXT, course_code TEXT, bank_id INTEGER, partial TEXT, pool TEXT, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS contest_scope_course ON contest_scope(course_code);
CREATE INDEX IF NOT EXISTS contest_scope_org ON contest_scope(org_id);
CREATE TABLE IF NOT EXISTS org_brand (org_id TEXT PRIMARY KEY REFERENCES orgs(id), slug TEXT NOT NULL UNIQUE, color TEXT, logo TEXT, tagline TEXT, description TEXT, website TEXT, updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS org_invites (org_id TEXT NOT NULL REFERENCES orgs(id), email TEXT NOT NULL, role TEXT NOT NULL, invited_by TEXT, created_at INTEGER NOT NULL, PRIMARY KEY (org_id, email));
CREATE INDEX IF NOT EXISTS org_invites_email ON org_invites(email);
CREATE TABLE IF NOT EXISTS contest_options (code TEXT PRIMARY KEY REFERENCES contests(code), guests INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS guests (user_id TEXT PRIMARY KEY REFERENCES users(id), channel TEXT NOT NULL, contact TEXT NOT NULL, verified_by TEXT NOT NULL, created_at INTEGER NOT NULL, verified_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS guests_contact ON guests(contact);
CREATE TABLE IF NOT EXISTS verify_codes (id TEXT PRIMARY KEY, channel TEXT NOT NULL, contact TEXT NOT NULL, code_hash TEXT NOT NULL, data TEXT NOT NULL, ip TEXT, attempts INTEGER NOT NULL DEFAULT 0, expires_at INTEGER NOT NULL, used_at INTEGER, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS verify_codes_contact ON verify_codes(contact, created_at);
CREATE INDEX IF NOT EXISTS verify_codes_ip ON verify_codes(ip, created_at);
CREATE TABLE IF NOT EXISTS contact_consents (user_id TEXT NOT NULL REFERENCES users(id), org_id TEXT NOT NULL REFERENCES orgs(id), marketing INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, PRIMARY KEY (user_id, org_id));
CREATE TABLE IF NOT EXISTS user_blocks (user_id TEXT PRIMARY KEY, reason TEXT, blocked_by TEXT, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS salas (code TEXT PRIMARY KEY, juego TEXT NOT NULL, host_id TEXT NOT NULL REFERENCES users(id), org_id TEXT, acceso TEXT NOT NULL, titulo TEXT, premio TEXT, estado TEXT NOT NULL, jugadores INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, ended_at INTEGER);
CREATE INDEX IF NOT EXISTS salas_host ON salas(host_id, created_at);
CREATE INDEX IF NOT EXISTS salas_org ON salas(org_id, created_at);
CREATE TABLE IF NOT EXISTS sala_jugadores (code TEXT NOT NULL, user_id TEXT NOT NULL, nombre TEXT, puesto INTEGER, puntos INTEGER, created_at INTEGER NOT NULL, PRIMARY KEY (code, user_id));
CREATE TABLE IF NOT EXISTS preguntas_vistas (quien TEXT NOT NULL, qid TEXT NOT NULL, visto_at INTEGER NOT NULL, PRIMARY KEY (quien, qid));
CREATE INDEX IF NOT EXISTS preguntas_vistas_fecha ON preguntas_vistas(quien, visto_at);
CREATE TABLE IF NOT EXISTS contest_seq (code TEXT NOT NULL, user_id TEXT NOT NULL, qids TEXT NOT NULL, created_at INTEGER NOT NULL, PRIMARY KEY (code, user_id));
CREATE TABLE IF NOT EXISTS contest_areas (code TEXT PRIMARY KEY, areas TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS cuestionario_opciones (code TEXT PRIMARY KEY, modo TEXT NOT NULL DEFAULT 'examen', grupo_id INTEGER, explica INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS practica_intentos (id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT NOT NULL, user_id TEXT NOT NULL, aciertos INTEGER NOT NULL, total INTEGER NOT NULL, ms INTEGER NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS practica_intentos_user ON practica_intentos(code, user_id);
CREATE TABLE IF NOT EXISTS course_groups (id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT NOT NULL, name TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS course_groups_code ON course_groups(code);
CREATE TABLE IF NOT EXISTS course_group_members (code TEXT NOT NULL, user_id TEXT NOT NULL, group_id INTEGER NOT NULL, PRIMARY KEY (code, user_id));
CREATE TABLE IF NOT EXISTS course_invites (code TEXT NOT NULL, email TEXT NOT NULL, name TEXT, student_code TEXT, invited_by TEXT, created_at INTEGER NOT NULL, PRIMARY KEY (code, email));
CREATE INDEX IF NOT EXISTS course_invites_email ON course_invites(email);
CREATE TABLE IF NOT EXISTS org_planes (org_id TEXT PRIMARY KEY, plan TEXT NOT NULL DEFAULT 'gratis', cuota INTEGER NOT NULL DEFAULT 0, hasta INTEGER, nota TEXT, updated_at INTEGER NOT NULL, updated_by TEXT);
CREATE TABLE IF NOT EXISTS ia_uso (org_id TEXT NOT NULL, mes TEXT NOT NULL, usos INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (org_id, mes));
CREATE TABLE IF NOT EXISTS ia_explicaciones (clave TEXT PRIMARY KEY, texto TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS mis_bancos (id INTEGER PRIMARY KEY AUTOINCREMENT, owner_id TEXT NOT NULL REFERENCES users(id), name TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS mis_bancos_owner ON mis_bancos(owner_id);
CREATE TABLE IF NOT EXISTS mis_preguntas (id INTEGER PRIMARY KEY AUTOINCREMENT, banco_id INTEGER NOT NULL, q TEXT NOT NULL, opts TEXT NOT NULL, answer INTEGER NOT NULL DEFAULT 0, level INTEGER NOT NULL DEFAULT 1, topic TEXT, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS mis_preguntas_banco ON mis_preguntas(banco_id);
CREATE TABLE IF NOT EXISTS reto_preguntas (event_code TEXT PRIMARY KEY, fuente TEXT NOT NULL, nombre TEXT, pool TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS bank_question_extra (question_id INTEGER PRIMARY KEY, tipo TEXT NOT NULL DEFAULT 'opcion', num TEXT, imagen TEXT, opt_imgs TEXT, desarrollo TEXT);
CREATE TABLE IF NOT EXISTS preguntas_imagenes (id TEXT PRIMARY KEY, org_id TEXT, owner_id TEXT NOT NULL, tipo TEXT NOT NULL, data TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS preguntas_imagenes_owner ON preguntas_imagenes(owner_id, created_at);
CREATE TABLE IF NOT EXISTS contest_textos (code TEXT NOT NULL, user_id TEXT NOT NULL, idx INTEGER NOT NULL, texto TEXT NOT NULL, estado TEXT NOT NULL, comentario TEXT, revisado_por TEXT, revisado_at INTEGER, created_at INTEGER NOT NULL, PRIMARY KEY (code, user_id, idx));
CREATE TABLE IF NOT EXISTS repasos (id INTEGER PRIMARY KEY AUTOINCREMENT, bank_id INTEGER NOT NULL, org_id TEXT, titulo TEXT NOT NULL, descripcion TEXT, n INTEGER NOT NULL DEFAULT 10, origen TEXT NOT NULL DEFAULT 'institucion', publicado_por TEXT NOT NULL, activo INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS repaso_codigos (codigo TEXT PRIMARY KEY, repaso_id INTEGER, org_id TEXT, dias INTEGER NOT NULL, usos_max INTEGER NOT NULL DEFAULT 1, usos INTEGER NOT NULL DEFAULT 0, nota TEXT, creado_por TEXT NOT NULL, vence INTEGER, created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS repaso_accesos (user_id TEXT NOT NULL, alcance TEXT NOT NULL, hasta INTEGER NOT NULL, codigo TEXT, created_at INTEGER NOT NULL, PRIMARY KEY (user_id, alcance));
CREATE TABLE IF NOT EXISTS repaso_intentos (id INTEGER PRIMARY KEY AUTOINCREMENT, repaso_id INTEGER NOT NULL, user_id TEXT NOT NULL, plan TEXT NOT NULL, respuestas TEXT NOT NULL DEFAULT '{}', aciertos INTEGER NOT NULL DEFAULT 0, total INTEGER NOT NULL, created_at INTEGER NOT NULL, terminado_at INTEGER);
CREATE INDEX IF NOT EXISTS repaso_intentos_user ON repaso_intentos(user_id, repaso_id, created_at);
CREATE TABLE IF NOT EXISTS campanas (code TEXT PRIMARY KEY, org_id TEXT NOT NULL, owner_id TEXT NOT NULL, nombre TEXT NOT NULL, descripcion TEXT, juego TEXT NOT NULL, intentos INTEGER NOT NULL DEFAULT 3, publico INTEGER NOT NULL DEFAULT 1, invitados INTEGER NOT NULL DEFAULT 1, ranking INTEGER NOT NULL DEFAULT 1, premios TEXT, umbral INTEGER, umbral_premio TEXT, seed INTEGER NOT NULL, starts_at INTEGER NOT NULL, ends_at INTEGER NOT NULL, cerrada_at INTEGER, premiados_at INTEGER, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS campanas_org ON campanas(org_id, ends_at);
CREATE TABLE IF NOT EXISTS campana_intentos (id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT NOT NULL, user_id TEXT NOT NULL, n INTEGER NOT NULL, seed INTEGER NOT NULL, started_at INTEGER NOT NULL, finished_at INTEGER, score INTEGER, seconds INTEGER, created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS campana_intentos_code ON campana_intentos(code, user_id);
CREATE TABLE IF NOT EXISTS campana_cupones (codigo TEXT PRIMARY KEY, code TEXT NOT NULL, user_id TEXT NOT NULL, tipo TEXT NOT NULL, puesto INTEGER, premio TEXT NOT NULL, created_at INTEGER NOT NULL, canjeado_at INTEGER, canjeado_por TEXT);
CREATE INDEX IF NOT EXISTS campana_cupones_code ON campana_cupones(code, user_id);
CREATE TABLE IF NOT EXISTS campana_maraton (code TEXT PRIMARY KEY, reglas TEXT NOT NULL, tableros TEXT);
CREATE TABLE IF NOT EXISTS campana_progreso (intento_id INTEGER PRIMARY KEY, code TEXT NOT NULL, estado TEXT NOT NULL, vence_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS campana_progreso_code ON campana_progreso(code, vence_at);
